In [1]:
import numpy as np

### Creating Numpy Array

In [3]:
a=np.array([
    [1,2],
    [3,4]
]) #2x2
a

array([[1, 2],
       [3, 4]])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [7]:
a.ndim

2

In [8]:
a.size

4

In [9]:
a.shape #tuple(row,col)

(2, 2)

### np.ones

In [11]:
arr=np.ones((10,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### np.zeros

In [12]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.full

In [13]:
arr=np.full((3,3),5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## Array with Random Values 

### np.random.random

In [16]:
arr=np.random.random((3,3)) # 0-1 
arr

array([[0.85643221, 0.89162996, 0.52840112],
       [0.993911  , 0.10282665, 0.26916101],
       [0.9734991 , 0.30566884, 0.41174372]])

### np.random.randint

In [20]:
arr=np.random.randint(0,50,(3,3)) #low,high,shape(row,col)
arr

array([[23,  3,  1],
       [43, 24, 45],
       [30, 47, 39]])

## Array with Sequence

### np.arange

In [25]:
arr=np.arange(0,30,5)
arr

array([ 0,  5, 10, 15, 20, 25])

### np.linspace

In [24]:
arr=np.linspace(0,5,10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Reshaping Array

In [29]:
arr=np.arange(1,24,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [30]:
arr.size

12

In [31]:
arr.shape

(12,)

In [37]:
arr.reshape(6,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

In [38]:
arr.reshape(1,-1) #one row and n columns

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

In [39]:
arr.reshape(-1,1) #n rows and 1 column

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23]])

In [43]:
arr.reshape(2,2,3) #12 => 3,4 => 2x2x3 

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13, 15, 17],
        [19, 21, 23]]])

### Flatten Array

In [41]:
arr.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [44]:
np.ravel(arr)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [45]:
np.hstack(arr)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [46]:
np.vstack(arr)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23]])

## Array Indexing

In [47]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a[1][1] #array[row][col]

5

### Slicing

array[start:stop:step,start:stop:step] => array[row,col]

In [50]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [51]:
# 1st
a[::2,::2]

array([[1, 3],
       [7, 9]])

In [53]:
# 2 nd
a[1:2:1,1:2:1]

array([[5]])

In [54]:
# 3rd
a[::2,:]

array([[1, 2, 3],
       [7, 8, 9]])

## Arrays with Operators

In [55]:
a=np.array([
    [1,2],
    [3,4]
])
a

array([[1, 2],
       [3, 4]])

In [56]:
a+1

array([[2, 3],
       [4, 5]])

In [57]:
a-2

array([[-1,  0],
       [ 1,  2]])

In [58]:
a*3

array([[ 3,  6],
       [ 9, 12]])

In [59]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

### Transpose

In [60]:
a.T

array([[1, 3],
       [2, 4]])

## Array Methods

#### arr.max

In [62]:
a

array([[1, 2],
       [3, 4]])

In [61]:
a.max()

4

In [63]:
a.max(axis=1) #row-wise max elements

array([2, 4])

In [64]:
a.max(axis=0) #col-wise max elements

array([3, 4])

#### arr.min

In [66]:
a.min()

1

In [67]:
a.min(axis=1) #row-wise min elements 

array([1, 3])

In [68]:
a.min(axis=0) #col-wise min elements

array([1, 2])

#### arr.sum()

In [69]:
a.sum()

10

#### arr.cumsum()

In [70]:
a.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [71]:
a.cumsum(axis=1)

array([[1, 3],
       [3, 7]], dtype=int32)

In [72]:
a.cumsum(axis=0)

array([[1, 2],
       [4, 6]], dtype=int32)

#### np.pi

In [74]:
np.pi

3.141592653589793

#### np.sin

In [75]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

#### np.exp

In [76]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

#### np.sqrt

In [77]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### np.sort

In [78]:
np.sort(a)

array([[1, 2],
       [3, 4]])

In [79]:
np.sort(a,axis=0) #col sorting

array([[1, 2],
       [3, 4]])

## Array Operations

In [81]:
b=np.array([
    [3,6],
    [7,8]
])
b

array([[3, 6],
       [7, 8]])

In [83]:
a+b

array([[ 4,  8],
       [10, 12]])

In [84]:
a-b

array([[-2, -4],
       [-4, -4]])

In [85]:
a*b #element to elememt multiplication

array([[ 3, 12],
       [21, 32]])

In [86]:
#matrix multiplication
a.dot(b)

array([[17, 22],
       [37, 50]])

### Spliting Array

In [97]:
a=np.random.randint(1,10,(4,4))
a

array([[9, 6, 4, 1],
       [9, 9, 2, 4],
       [3, 1, 8, 7],
       [8, 1, 6, 7]])

#### np.hsplit

In [98]:
np.hsplit(a,2) #split along horizontal axis

[array([[9, 6],
        [9, 9],
        [3, 1],
        [8, 1]]),
 array([[4, 1],
        [2, 4],
        [8, 7],
        [6, 7]])]

#### np.vsplit

In [99]:
np.vsplit(a,2) #split along vertical axis

[array([[9, 6, 4, 1],
        [9, 9, 2, 4]]),
 array([[3, 1, 8, 7],
        [8, 1, 6, 7]])]

### Working on Date with Numpy

In [104]:
np.datetime64('2022-04-05')

numpy.datetime64('2022-04-05')

In [101]:
date=np.arange('2021-01','2022-01',dtype="datetime64[D]")
date

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
       '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
       '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
       '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
       '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
       '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
       '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
       '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
       '2021-03-02', '2021-03-03', '2021-03-04', '2021-

In [103]:
#timedelta
np.datetime64('2022-04-05')-np.datetime64('2022-04-02')

numpy.timedelta64(3,'D')

### Linear Algebra in Numpy

In [105]:
a

array([[9, 6, 4, 1],
       [9, 9, 2, 4],
       [3, 1, 8, 7],
       [8, 1, 6, 7]])

In [106]:
np.linalg.matrix_rank(a) #rank of matrix

4

In [108]:
np.linalg.eig(a)

(array([21.01852336+0.j        ,  1.28250433+2.71457438j,
         1.28250433-2.71457438j,  9.41646797+0.j        ]),
 array([[ 0.47687777+0.j        ,  0.08964055-0.47445698j,
          0.08964055+0.47445698j, -0.33659465+0.j        ],
        [ 0.59187251+0.j        , -0.08524568+0.44223237j,
         -0.08524568-0.44223237j, -0.53888844+0.j        ],
        [ 0.42135664+0.j        ,  0.41284597+0.31289037j,
          0.41284597-0.31289037j,  0.6834055 +0.j        ],
        [ 0.49470507+0.j        , -0.5437616 +0.j        ,
         -0.5437616 -0.j        ,  0.35952777+0.j        ]]))